# Importing All important Libary & Dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('insurance.csv')

In [3]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [51]:
df.isnull().sum() #no null value is detected

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [53]:
df1=df.copy()
df2=df.copy()
df3=df.copy()


# Label Encoder

In [54]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [55]:
from pandas.core.dtypes.common import is_numeric_dtype

In [56]:
for col in df1.columns:
    if is_numeric_dtype(df1[col]):
        continue
    
    df1[col] = le.fit_transform(df1[col])

In [57]:
df1.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

# One Hot Encoding

In [58]:
from pandas.core.dtypes.common import is_numeric_dtype

In [59]:
for col in df2.columns:
    if is_numeric_dtype(df2[col]):
        continue
    
    one_hot = pd.get_dummies(df2[[col]],drop_first=True,prefix='Dummy')
    df2 = pd.concat([df2,one_hot], axis=1).drop(col,axis=1)

In [60]:
df2.head()

age     bmi  children      charges  Dummy_male  Dummy_yes  Dummy_northwest  \
0   19  27.900         0  16884.92400           0          1                0   
1   18  33.770         1   1725.55230           1          0                0   
2   28  33.000         3   4449.46200           1          0                0   
3   33  22.705         0  21984.47061           1          0                1   
4   32  28.880         0   3866.85520           1          0                1   

   Dummy_southeast  Dummy_southwest  
0                0                1  
1                1                0  
2                1                0  
3                0                0  
4                0                0

# Ordinal Encoder

In [61]:
gender = df3.sex.unique()
cigerete = df3.smoker.unique()
direction = df3.region.unique()

In [62]:
gender , cigerete , direction

(array(['female', 'male'], dtype=object),
 array(['yes', 'no'], dtype=object),
 array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object))

In [63]:
from sklearn.preprocessing import OrdinalEncoder

In [64]:
ordi1 = OrdinalEncoder (categories = [gender])
ordi2 = OrdinalEncoder(categories = [cigerete])
ordi3 = OrdinalEncoder(categories = [direction])

In [65]:
encodded_value1 = ordi1.fit_transform(df3[['sex']])
encodded_value2 = ordi2.fit_transform(df3[['smoker']])
encodded_value3 = ordi3.fit_transform(df3[['region']])

In [66]:
encodded_value1, encodded_value2, encodded_value3

(array([[0.],
        [1.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [0.]]),
 array([[0.],
        [1.],
        [1.],
        ...,
        [1.],
        [0.],
        [2.]]))

In [67]:
df3['sex'] = pd.DataFrame(encodded_value1)
df3['smoker'] = pd.DataFrame(encodded_value2)
df3['region'] = pd.DataFrame(encodded_value3)

In [68]:
df3

age  sex     bmi  children  smoker  region      charges
0      19  0.0  27.900         0     0.0     0.0  16884.92400
1      18  1.0  33.770         1     1.0     1.0   1725.55230
2      28  1.0  33.000         3     1.0     1.0   4449.46200
3      33  1.0  22.705         0     1.0     2.0  21984.47061
4      32  1.0  28.880         0     1.0     2.0   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50  1.0  30.970         3     1.0     2.0  10600.54830
1334   18  0.0  31.920         0     1.0     3.0   2205.98080
1335   18  0.0  36.850         0     1.0     1.0   1629.83350
1336   21  0.0  25.800         0     1.0     0.0   2007.94500
1337   61  0.0  29.070         0     0.0     2.0  29141.36030

[1338 rows x 7 columns]